### PR TITLE
Fix saucelabs scope

### PR DESCRIPTION
**Pull request by NickColley**
Seeing if zuul update fixes ie10-11

### CODE REVIEW

**Comment by varjmes** [comment]
Sadly it doesn't seem to fix the IE 10/11 situation. Always good to update dependencies though so we may as well update zuul anyway?

**Comment by gr2m** [comment]
yeah why note, if it doesn't break our current tests

**Comment by NickColley** [comment]
We have a few out of date devDeps: https://david-dm.org/hoodiehq/pouchdb-hoodie-api#info=devDependencies

**Comment by varjmes** [comment]
I say give the update a go :+1:

**Comment by gr2m** [comment]
yeah, +1, let's close this one and make a separate PR to update all dependencies, and see if tests pass

**Pull request closed without merging**
