### PR TITLE
added more testing browsers to specs https://github.com/boennemann/pouch...

### PR DESCRIPTION
**Pull request by zoepage**
...db-hoodie-api/issues/1

### CODE REVIEW

**Comment by gr2m** [comment]
We've to fix the configuration issue, so all tests pass before we can merge it and close #1. Once that's done, fixup your commit to follow the commit message conventions. Let me know if you have any questions :)

**Comment by zoepage** [comment]
Looks like it fails bc the .zuulrc is missing, but I don't want to add the credentials to the repo... any ideas?

**Comment by boennemann** [comment]
`.zuulrc` needs to be part of the repo. You can add the credentials via encrypted env vars :)
Here are instructions: https://github.com/defunctzombie/zuul/wiki/Travis-ci#5-final-step

**Comment by boennemann** [comment]
I just noticed you can't do this, because it's a personal repo. Move to hoodiehq first?

**Comment by zoepage** [comment]
Status @boennemann ? :)

**Comment by gr2m** [comment]
I guess this is fixed via https://github.com/hoodiehq/pouchdb-hoodie-api/commit/458f86a0272ce1be7fca8c97490a5656adc4d01b

**Pull request closed without merging**
