### PR TITLE
[chore] Update zuul config to test more browsers

### LINKED ISSUE #28: SauceLabs not currently testing on >IE10 or mobile safari
"Test are currently not running on >IE10 and mobile Safari. This is likely an error with the setup and we would be more than happy if you'd want to fix that :)"

### PR DESCRIPTION
**Pull request by lewiscowper**
Wanted to test this, so hopefully saucelabs will kick off on a PR. But this should fix #28 if merged.

/cc @boennemann in case it won't run the tests for a PR.

### CODE REVIEW

**Comment by boennemann** [comment]
@lewiscowper Thanks :) Saucelabs indeeds runs PRs. Sorry for ne being clear enough here though. The tests run in these browsers, it's just that they fail.

My current guess is a missing Promise polyfill, but simply adding one didn't fix things either :/

**Comment by lewiscowper** [comment]
Aha! So I'm watching the build on Travis, and the two that are failing are IE10 and IE11.

```
- waiting: <internet explorer 11 on Windows 2012 R2>
- waiting: <internet explorer 10 on Windows 2012>
```

It seems like the iphone tests actually run on OS X, which seems unusual, so ¯_(ツ)_/¯

Maybe adding the promise polyfill fixed it on iphone but not on IE? How does pouchdb handle them?

**Comment by gr2m** [comment]
fyi there is a new major zuul version out, maybe that'll help somehow?

**Comment by gr2m** [comment]
let's close this for now, we'll look into it later

**Pull request closed without merging**
