### PR TITLE
PouchDB Memory

### PR DESCRIPTION
**Pull request by gr2m**
PouchDB now supports custom builds and we should take advantage of that to speed up installs and Travis builds :)

### CODE REVIEW

**Comment by gr2m** [comment]
ping @hoodiehq/maintainers

**Comment by varjmes** [comment]
LGTM! 🎉

**Comment by rogeriochaves** [comment]
LGTM!

**Comment by nolanlawson** [comment]
I basically started doing this for all pouchdb plugins. Waaaay faster, npm install vastly sped up, test itself is faster because it's all in-memory. :+1:

**Comment by gr2m** [comment]
Thanks y’all <3

**Pull request merged**
