### PR TITLE
avoid usage of uuid() in tests

### PR DESCRIPTION
**Pull request by gr2m**
using random anything in tests is not good practise.
In this case we can simply have a counter that increases
each time we call the dbFactory, does the same thing.

### CODE REVIEW

**Comment by gr2m** [comment]
@zoepage @patriciagarcia can we merge this?

**Comment by janl** [comment]
what problem does this solve?

**Comment by zoepage** [comment]
+1

**Comment by gr2m** [comment]
> what problem does this solve?

avoids usage of randomization in tests, besides being cleaner and faster

**Comment by janl** [comment]
I don’t understand what “avoids usage of randomization in tests” means, sorry :)

**Comment by janl** [comment]
or rather, why this is bad

**Comment by gr2m** [comment]
because in test setups, you want a 100% reproducible setup. Let's say there would be some weird error in PouchDB that would crash but only if the dbname starts with "x", then all of the sudden your tests would fail 1 in a 1k. You'd see the error, run the exact same test again, and it would give you a different result. That's something you want to avoid when testing, right?

**Comment by janl** [comment]
yup, got it.

My assumption was that these kinds of things don’t error :)

**Comment by janl** [comment]
thanks for taking the time to explain this!

**Comment by varjmes** [comment]
Makes sense to me :)

**Comment by HipsterBrown** [comment]
I just want to say how much I've enjoyed following this thread. The knowledge share is pretty awesome. 👍

**Comment by lewiscowper** [comment]
I get the reasons to not use a randomly generated string in tests, because you lack control and reproducibility, but random test failures, as you describe with the "dbname begins with x" suggestion, are surely indicative of a deeper problem. Is it worthwhile to test a wide range of potential user inputs to try and cover things like that? For example, multi-byte characters, non-latin alphabet characters, numbers etc. (Might not be as useful in this instance, but in general)

**Comment by gr2m** [comment]
@lewis yeah, but that is out of scope here, this should go in PouchDB tests. And I assume it's very well tested :)

**Comment by janl** [comment]
@lewiscowper like @gr2m said, you are absolutely right, but this particular test doesn’t actually test the naming of databases, that’s just a side-effect of what is actually being tested, so those things wouldn’t belong here. I agree that they should live in PouchDB land.

**Pull request merged**
