### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by gr2m**
# WIP - do not merge

Current state of discussion:
## 1. Suggestion _factory method_
- a `db.hoodieApi()` method, that returns the API
- clarify in `README.md` that the plugin is just API sugar for PouchDB / CouchDB, it does not work against Hoodie server.
- Idea 1b: don't call it _hoodie_ directly, but _hoodielike_, _hoodiesque_, etc. For example: `db.getHoodielikeApi()`

``` js
PouchDB.plugin('hood', require('pouchdb-hoodie-ap'));
var db = new PouchDB(options)
var api = db.hoodieApi();

api.add({foo: 'bar'})
 // etc
```
## 2. Suggestion _namespace_
- rename plugin to `pouchdb-hood`
- extend the existing `PouchDB.plugin()` method to accept a namespace as first argument
- Idea 2b: Call namespace `store`, instead of `hood`

``` js
PouchDB.plugin('hood', require('pouchdb-hoodie-ap'));
var db = new PouchDB()
db.hood.add({foo: 'bar'})
 // etc
```

---

For both suggestions, all methods can be required separately

```
PouchDB.plugin({
  update: require('pouchdb-hoodie-api/update')
})
```

### CODE REVIEW

**Comment by boennemann** [comment]
Where is `db.objects` coming from?

http://pouchdb.com/api.html#plugins

**Comment by gr2m** [comment]
I dunno, I just start with dreamcode :) what's yours?

How about 

``` js
var store = new PouchDB('dbname').getHoodieApi();
```

But as much as I love to see hoodie in there, I wonder if this will confuse people. Maybe we should call the thing something more generic.

**Comment by zoepage** [comment]
I can see both sides. 
  `var store = new PouchDB('dbname').getServerApi();` would always work for me. But I really like the idea, if it includes the word `hoodie`. 

I'd give `var store = new PouchDB('dbname').getHoodieApi();` a run :)

**Comment by gr2m** [comment]
I've discussed with @zoepage, we came up with

``` js
db = new PouchDB(options)
api = new PouchObjectsApi(db)
api.add(...) // etc
```

I think that's what @boennemann initially had in mind, too, right?

**Comment by janl** [comment]
the first line even could be made optional:

```
api = new PouchObjectsApi(options)
api.add(...) // etc
```

**Comment by gr2m** [comment]
Yeah, depends on wether we want to depend on PouchDB in package.json dependencies or not. As this is a plugin, I'd say we should not depend on `pouchdb`.

**Comment by gr2m** [comment]
I though more about this, and I think that actually the nicest thing would be to simply have 

``` js
db.objects.add()
// etc
```

The current [PouchDB.plugin API](http://pouchdb.com/api.html#plugins) does not allow for a namespace, but I'd suggest they add the ability to do so, by optionally passing a function instead of an object, like we do with hoodie.

If that'd be in place, the code would simply be in the browser:

``` html
<script src="pouchdb.js"></script>
<script src="pouchdb.objects-api.js"></script>
```

and in node

``` js
var PouchDB = require('pouchdb')
var objectsApi = require('pouchdb-objects-api')
PouchDB.plugin(objectsApi)
```

I think that'd be the nicest from a user's perspective

**Comment by adamyeats-zz** [comment]
I think you should be clearer about what `objects` are. I believe this denotes that these are Hoodie objects, but I can't be sure. 

Also, from a true beginner's perspective: hey, this thing is called "objects". Does this mean I can't store arrays in it, for example?

**Comment by zoepage** [comment]
Had the same thought then @adamyeats about the naming of the `objects`. It doesn't seem 100% clear, especially from a beginner perspective.

**Comment by gr2m** [comment]
@adamyeats yes, you can store arrays: `db.objects.add([{foo: 'bar'}, {foo: 'baz'}])`. And these are not Hoodie objects, this has nothing to do with Hoodie at this point, it stores JavaScript objects.

I just don't want to call it `hoodie`, because it's not compatible with the hoodie server yet. It should be called something that explains what it does, and that is useable for the PouchDB community. Hoodie will just use it internally for it's own API.

I think storing objects is what I want to do, and then retrieving them later, or changing their properties. I can't think of a better name. Any suggestions?

**Comment by adamyeats-zz** [comment]
@gr2m 

> yes, you can store arrays: db.objects.add([{foo: 'bar'}, {foo: 'baz'}])

Yeah, sure. So that's obvious to me with 4 years experience behind me, but would have been less obvious within the first year.

I'm trying to think of a better name (no luck yet) but I think it should be more explicit that this is a data store rather than `objects` which is quite a broad, overloaded term.

**Comment by janl** [comment]
I agree that `objects` is problematic. would `store` work?

> db.store.add()

**Comment by gr2m** [comment]
> Yeah, sure. So that's obvious to me with 4 years experience behind me, but would have been less obvious within the first year.

We can clarify in the readme, what we mean by objects? 

> I agree that objects is problematic. would store work?

I find this confusing, because PouchDB is already a store.

---

Another aspect of this plugin is that it aims to simplify the interaction with the database. Maybe we find a good name that expresses that? 

Or, we call it `pochi`. That's swahili for pouch. And I think it sounds super cool :)

**Comment by adamyeats-zz** [comment]
> I agree that objects is problematic. would store work?

I almost definitely prefer this.

> We can clarify in the readme, what we mean by objects?

I mean, sure, you could do that, but I think that's skirting around the issue by making the developer read more rather than fixing it. I'm not sure if the solution to "simplify the interaction with the database" is to pretend that it's not there, which is what it seems like to me.

**Comment by boennemann** [comment]
I would really like this to be a PouchDB plugin, using the `.plugin()` API and not a wrapper like it's currently implemented. I tried to think of my dream API and at first I liked this one pretty much:

``` js
PouchDB.plugin(store)
var db = new PouchDB('dbname')
db.store.add(…)
```

With the current pouchdb API it's not possible to achieve this without calling an initializer like `db.store()` first though. To expose the proper `this` context to the individual methods another function call is needed. "It's not possible" is usually not an excuse to give up on your API, but while desperately trying to hack around this limitation I began to ask myself whether the namespacing is required in the first place.

We can't even find a name for such a namespace. I think that's because the PouchDB instance is already the store or object or pochi or _thing_ we are working on. Unfortunately the PouchDB instance's public API collides with Hoodie's `remove` method, so we can't just add all the methods directly like so: 

``` js
db.add(…)
db.update(…)
db.remove(…) //boom
```

The conflict aside, this is what I'd like a lot more though, both on a maintainer and consumer side.
For a consumer I've got one single object to handle. As the methods are attached to the db object, together with their obvious names, it should become pretty clear what they're supposed to do.
The implementation get's easier as well. `this` is always referring to the PouchDB instance, where the data and methods, but also all internal APIs and helpers are exposed. (Think `this.emit('add',{…})` for example, or `this.PouchDB.utils`))

An idea of how we could still make this work is this then:

``` js
db.$add()
db.$update()
db.$remove()
```

It gives the additional benefit that you're always aware you're using the hoodie API (no `_id`, but `id` etc). Additionally there could be a method to return an object with all Hoodie methods bound to the PouchDB instance, but without the `$` prefix.

``` js
var store = db.getStore()
store.add()
store.update()
store.remove()
```

I hope this is at least a nudge in the right direction :)

For the name of the npm module itself I think `pouchdb-hoodie-api` is a very good name, because it's a precise and concise description of what it is. The Hoodie Store API for PouchDB.

**Comment by janl** [comment]
@boennemann well thought out and I think I agree with your proposal!

**Comment by boennemann** [comment]
I guess at this point we have all agreed that this should be a real plugin.
This is why I have rewritten every single method so that it can be exposed as a PouchDB method on this branch: https://github.com/hoodiehq/pouchdb-hoodie-api/tree/refactor-plugin

Thanks to this we have a bunch of methods that can all be individually used as a plugin.

E.g. 

``` js
PouchDB.plugin({
  add: require('pouchdb-hoodie-api/add')
})
```

or even the helpers

``` js
PouchDB.plugin({
  add: require('pouchdb-hoodie-api/helpers/add-one')
})
```

The API we expose by default is now solely defined by this file: https://github.com/hoodiehq/pouchdb-hoodie-api/blob/refactor-plugin/lib/index.js

``` js
module.exports = {
  $add: require('./add'),
  $find: require('./find'),
  $findAll: require('./find-all'),
  $findOrAdd: require('./find-or-add'),
  $update: require('./update'),
  $updateOrAdd: require('./update-or-add'),
  $updateAll: require('./update-all'),
  $remove: require('./remove')
}
```

All it takes to change to a namespaced `store.add()` API is changing the file like so:

``` js
module.exports = {
  store: function () {
    return {
      add: require('./add').bind(this),
      find: require('./find').bind(this),
      findAll: require('./find-all').bind(this),
      findOrAdd: require('./find-or-add').bind(this),
      update: require('./update').bind(this),
      updateOrAdd: require('./update-or-add').bind(this),
      updateAll: require('./update-all').bind(this),
      remove: require('./remove').bind(this)
    }
  }
}
```

Implementation details aside, we can now discuss which API we like the most :)
Even exposing multiple API's, or a function that let's you determine your own prefix (e.g. `$`, or 'hoodie-') isn't a problem anymore. Get creative :)

**Comment by gr2m** [comment]
Great thoughts, Stephan! I very much prefer the .store() method that returns the api. The $ prefix is not really a nice api, it feels more like a hack. The .store() option also allows us to pass options, too. For the name, I'd call it like the function: "PouchDB-store". I agree that's pouchdb-hoodie-api describes what it is, but without our insights, one could easy interpret it as an API that is working against a Hoodie server, which it doesn't. But if you don't like that, I'd be fine if we clarify that in the plugin description / readme

**Comment by boennemann** [comment]
`$` is a hack, just like `store` is, I find both unsatisfying (`store` a little bit more even). So here is another proposal:
If the first argument passed to remove is a string or an object with an `_id` property we pass it on to the PouchDB method. This allows us to expose all methods unprefixed w/o breaking any code.

**Comment by adamyeats-zz** [comment]
:+1: to @boennemann's proposals. Wondering if the latter proposal might be a bit too implicit? I'm struggling to think of how this could be a drawback right now.

**Comment by gr2m** [comment]
two more ideas, that might (or might not :) ) lead somewhere:

If we want to keep the `pouchdb-hoodie-api` name, I'd rather add a method `.hoodieApi()` than `.store()`, to stay consistent with the name.

Another idea would be to do this

``` js
api = require('pouchdb-hoodie-api')

PouchDB.prototype.store = {
  add: api.add.bind(PouchDB.prototype),
  remove: api.remove.bind(PouchDB.prototype),
  // etc
}
```

That will actually give us

``` js
db = new Pouchdb()
db.store.add(obj);
// etc
```

Now, at least for an Node.JS context, it would be nice to call something like `PouchDB.plugin(api)` to explicitly add the API. `.plugin` can't currently do that, so we could either send a pull request so that `.plugin` accepts an array or two arguments, to do something like

``` js
PouchDB.plugin(['store', api])
// or
PouchDB.plugin('store', api)
```

And for the time being, we could make our own plugin (or plugin patch) method as a PouchDB plugin :)

I still feel strong that the `$` prefix is not a good idea. But I really like the idea that every method could be required separately with doing something like `require('pouchdb-hoodie-api/add')` etc. That's great to optimize for file size when working in the browser.

**Comment by boennemann** [comment]
@gr2m Unfortunately binding to the prototype isn't the same as binding to this.

``` js
function logger() {
  console.log(this.a)
  console.log(this.b)
}

function PouchDB () {
  this.b = 'nope'
  this.store.remove = logger.bind(this)
}

PouchDB.prototype.a = 'yep'

PouchDB.prototype.store = {
  add: logger.bind(PouchDB.prototype)
}

var foo = new PouchDB()

foo.store.add()
// yep undefined
foo.store.remove()
// yep nope
```

We need a separate function call for this :/ 

Requiring individual methods already works on my branch though :)

**Comment by gr2m** [comment]
Another possibility is to submit a pull request to `PouchDB`, that will add a `PouchDB.on("init", handler)` API, in which the handler could manipulate the instance directly. I think if we agree that a `db.store.add` namespace solution is best, we'll find a way to make it work.

**Comment by daleharvey** [comment]
From the pouch side if theres a simple backwards compatible patch to extend the plugin api then pretty likely we will take it.

From the 'pretending to be a user' side I am not sure why you would want to try and mixin another api on top of / next to another incompatible api. 

Why wouldnt you:

   var store = new Hoodie(); 
   store.add();

or whatever you already do and just expose the hoodie api without any of the pouch one, only using it / wrapping it internally? if you want users do be able to switch backends you can have that as optional argument to your constructor.

**Comment by nolanlawson** [comment]
For [relational-pouch](https://github.com/nolanlawson/relational-pouch), I have an explicit init method, and from then on I provide a `.rel` API:

``` js
var db = new PouchDB('foo')
db.setSchema(...)
db.rel.find()
db.rel.save()
db.rel.del()
```

So there's no problem with namespace collisions. You could do something similar with `db.hoodie` or `db.store` etc.

As for the init handler, there is indeed a `PouchDB.on('created')` event ([see docs](http://pouchdb.com/api.html#events)), although it doesn't give you access to the object, only the name. I think adding a second event that works slightly differently would be kinda confusing. Is an explicit init method for Hoodie users out of the question?

I also like Dale's idea of just hiding the PouchDB API entirely.

**Comment by gr2m** [comment]
@daleharvey @nolanlawson Hoodie is out of scope here. We will use this plugin internally in Hoodie, where we will not expose PouchDB at all. But this plugin is meant to be a standard PouchDB plugin, that people can use, just providing a nice API on top of PouchDB's API, without having any other dependencies.

> PouchDB.on('created', function (dbName) {
>   // called whenver a db is created.
> });

This is not what I mean. This gets only called when a database gets created, so if the db already exists, it doesn't get called. What I mean is a callback that gets called at the end of the PouchDB constructor, so I can manipulate the `db` instance that `db = new PouchDB` gives me. So I could do something like

``` js
PouchDB.on('init', function() {
  this.store = {
    add: add.bind(this),
    // etc
  }
});
db = new PouchDB()
db.store.add({foo: 'bar'})
```

Makes sense?

**Comment by nolanlawson** [comment]
Hmm, I'd rather fold that into the plugin API instead of adding a new event listener. How about:

``` js
PouchDB.plugin('store', {
  add: function () {...}
})
```

If the first arg is a string, then it's interpreted as a namespace. This would be backwards-compatible.

**Comment by gr2m** [comment]
> PouchDB.plugin('store', {
>   add: function () {...}
> })

That'd be my preferred solution. But it will need some extra logic in the constructor, as the `store.add` needs to bi `.bind` to `this`. Binding it to `PouchDB.prototype` won't be enough, as I learned above :) But yeah, should be doable.

Anyone okay with this approach?

**Comment by janl** [comment]
@gr2m and I talked a bit about it in our weekly meeting.

There are a few issues here.
1. The right incarnation to load the Hoodie-like API plugin with PouchDB.
2. How to expose the Hoodie-like API methods and if this include a namespace of some sort (`db.store` or `new HoodieAPI()`, then what to call that namespace.
3. If it is called `HoodieAPI()` or `db.hoodie`, people might confuse this with something that can talk to a Hoodie backend, while this is just API sugar for PouchDB. Just `store` is a bit plain and confusing, too.

Possible solutions (just summing up):
1. I personally don’t care, but it seems there are a few good options on the table. Not worried about this one.
2. These options:
   - clobbering the PouchDB namespace, with or without `$` prefix: nice hack, but potentially very confusing.
   - exposing a new object `HoodieAPI` that itself depends on PouchDB would break the “PouchDB Plugin” paradigm. Also lead to issues if an app uses PouchDB version 2 and the plugin depends on version 1.
   - using a namespace: `db.hoodie` would work, see 3.
   - using a constructor function: `var db = new PouchDB(); var hoodieAPI = db.getHoodieAPI()` would also work, see 3.
3. <insert that quote about naming being hard> — We want to a void that people think they get a Hoodie backend compatible thing. So maybe we can use a clever-but-not-too-clever name:
   - `hoodielike` as in `db.hoodielike.add()` or `var hoodielike = db.getHoodieLikeAPI()`
   - `hoodieesque` as in `db.hoodieesque.add()` or `var hoodieesque = db.getHoodieesqueAPI()`
   - `hoodieish` as in `db.hoodieish.add()` or `var hoodielike = db.getHoodieishAPI()`
   - <insert your bikeshed here>

**Comment by gr2m** [comment]
how about `pouchdb.hood.add(obj)`? `pouchdb-hood` is kinda a cool name and works semantically in a way, as it's an API on top of PouchDB.

**Comment by adamyeats-zz** [comment]
> These options:

Out of the options that @janl has posted, I'm leaning towards option 3 (using a `store` namespace). While the `hoodieish` naming thing is certainly good thinking, I think this is probably not clear enough for most users.

**Comment by gr2m** [comment]
@adamyeats do you prefer `pouchdb.store.add(obj)` over `pouchdb.hood.add(obj)`? If so, why?

**Comment by janl** [comment]
After some more contemplation, I think this is the best approach:

```
var db = new PouchDB();
var hoodielike = db.getHoodielikeAPI();
hoodielike.add();
...
```

`getHoodielikeAPI()` could also be `getHoodieAPI()`. I sympathise with the potential confusion of the API not actually working against a Hoodie backend, but I think that’s going to be okay in the long run, if we document things properly.

**Comment by zoepage** [comment]
After thinking about this for some days, I'm with @janl 's approach, although I'd prefer `getHoodieAPI()`.

**Comment by adamyeats-zz** [comment]
@gr2m 

My preference would be for `pouchdb.store.add(obj)` as it's more obvious to me at a glance what this method call is doing.

In reality, though, I feel both of your suggestions could work. :)

**Comment by gr2m** [comment]
I guess one thing we agree on, is that we want to expose all methods separately, like so:

``` js
var PouchDB = require('pouchdb')
var myCustomApi = {
  add: require('pouchdb-hoodie-api/add'),
  find: require('pouchdb-hoodie-api/find'),
  update: require('pouchdb-hoodie-api/update'),
  remove: require('pouchdb-hoodie-api/remove')
}
PouchDB.plugin(myCustomApi)
var db = new PouchDB('dbname')
db.add({foo: 'bar'})
// etc
```

I've added it to the pull request description, and also updated the suggested solutions based on current state of the discussion

**Comment by gr2m** [comment]
had another "naming is hard" discussion with @zoepage and @janl. We suggest
1. the plugin is called `pouchdb-hoodie-api`
2. It exposes one factory method `db.hoodieApi()`
3. The factory method returns an object with the hoodie-inspired api

**Comment by nolanlawson** [comment]
:+1: I like it.

**Comment by gr2m** [comment]
So I guess this can be closed now, fixed via 
https://github.com/hoodiehq/pouchdb-hoodie-api/pull/22

**Comment by janl** [comment]
🎉💃

**Pull request closed without merging**
